language: node_js
node_js:
  - "8"
  - node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
        - npm run test
      after_script:
        - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
